return {
    ["Ranks"] = true,
    ["Achievements"] = true,
    ["Blinds"] = true,
    ["Decks"] = true,
    ["DeckSkins"] = true,
    ["Enhancements"] = true,
    ["Jokers"] = {
        ["Normal"] = true,
        ["Final"] = true,
        ["Jean-Paul"] = true,
        ["Versatile"] = true,
    },
    ["Tags"] = {
        ["Classic"] = true,
        ["Switches"] = true,
    },
    ["Consumables"] = {
        ["Tarots"] = true,
        ["Spectrals"] = true,
        ["Mathematics"] = true,
        ["Logics"] = true,
    },
    ["Vouchers"] = true,
    ["Stickers"] = true,
    ["CrossMod"] = {
        ["Cryptid"] = false,
        ["Bunco"] = true,
        ["CardSleeves"] = true,
        ["MoreFluff"] = true,
        ["FusionJokers"] = true,
    },
    ["Stakes"] = true,
    ["Challenges"] = true,
    ["Technical"] = {
        ["Experimental"] = false,
        ["Easter Eggs"] = true,
        ["Engineer Versatile Weight Limit"] = 100,
    },
}